### PR TITLE
Tooling/dotnetcore

### PR DESCRIPTION
**Pull request by tomasaschan**
This looks massive, but the code is actually unchanged (except for a couple of fixes in the test code, see the last commits). However, I have moved it to a folder structure more common when using `dotnet`.

I have also bumped the version to 0.1.0 - seemed appropriate, with a new target framework :)

The two maintenance scripts `CreateNuget.cmd` and `DeployNuget.cmd` are gone; the corresponding actions can now be done with the CLI:

* `dotnet pack -c Release -o "$(pwd)\nuget_packages"` (from powershell) creates packages in the `nuget_packages` folder (as before)
* `dotnet push nuget_packages/FSharpFriendlyDotnet.0.1.0.nupkg -k <your-api-key>` pushes the both the package and the symbols package to NuGet.org

### CODE REVIEW

**Comment by tomasaschan** [comment]
Also, if this library is abandoned and you'd like me to take over, just let me know. You could either send me the NuGet API keys to be able to update the package, or I'll upload it under another name under my own account.

**Comment by kbilsted** [comment]
Nice PR. Many thanks. I would keep the scripts but change them into the `dotnet` commands you show here in the PR. Remember to generate and push symbols. See https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages packages without symbols are pure rage inducing ;-)

I don't get to code F# alot these days, so sure you are welcome onboard the project. Do you have any ideas in mind for the future?

**Comment by tomasaschan** [comment]
Ah, I didn't realize you had appveyor hooked up. Do you want me to create an appveyor.yml with config?

I don't really have any specific ideas for the future, more than realizing that I'll probably find more APIs that could use a facade once I start using the library.

**Comment by kbilsted** [comment]
I usually script creation of packages so I don't forget. I prefer manual release rather than on each push ;) appveyor for testing would be a blast ;-)

**Comment by tomasaschan** [comment]
One workflow for releases I've used successfully is to build with AppVeyor and push pre-release packages on every build, and then push "real" packages on tagged releases, which can be created from the GitHub UI. That allows for manual control of what code goes into a new release of the package, while making incremental improvements available for consumption anyway.

**Comment by tomasaschan** [comment]
@kbilsted There, there is now an `.appveyor.yml` that configures the build to run `dotnet build`, `dotnet pack` and `dotnet test` and exposes the created nuget packages as build artifacts for inspection. It doesn't push any packages; if you want that, I can do that in a separate PR. For a streamlined flow there, it would probably be nice to bring in something like [GitVersion](http://gitversion.readthedocs.io/en/latest/) to manage version numbering.

There's also `CreateNuget.cmd` and `DeployNuget.cmd` which allows you to do the same things locally, with the same workflow you used to have.

If you wouldn't mind, it would be awesome if this could be merged and released to nuget.org, because I want to use it in one of my projects :)

**Comment by kbilsted** [comment]
many thanks for the changes ;)

**Comment by kbilsted** [comment]
reading https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages  it looks like we need `nuget push MyPackage.symbols.nupkg -source https://nuget.smbsrc.net/` instead

**Comment by tomasaschan** [comment]
Based on [this](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push) I think not; `dotnet nuget push` seems to do both.

In any case, it should be easy to test (for you, who has the API key) - if you run the current `DeployNuget.cmd`, does it push symbols?

**Comment by kbilsted** [comment]
info : Pushing FSharpFriendlyDotNet.0.1.0.nupkg to 'https://nuget.org'...
info :   PUT https://nuget.org/api/v2/package/
info :   Created https://nuget.org/api/v2/package/ 13111ms
info : Your package was pushed.
info : Pushing FSharpFriendlyDotNet.0.1.0.symbols.nupkg to 'https://nuget.org'...
info :   PUT https://nuget.org/api/v2/package/
info :   Conflict https://nuget.org/api/v2/package/ 646ms
error: Response status code does not indicate success: 409 (A package with ID 'FSharpFriendlyDotNet' and version '0.1.0'
 already exists and cannot be modified.).

**Comment by kbilsted** [comment]
for fun i tried

dotnet nuget push *.symbols.nupkg --source https://nuget.org
dotnet nuget push *.nupkg --source https://nuget.org

on a 0.1.1 release. 

this gives me the reverse error ;) 

C:\src\FSharpFriendlyDotNet\nuget_packages>dotnet nuget push *.symbols.nupkg --source https://nuget.org
info : Pushing FSharpFriendlyDotNet.0.1.1.symbols.nupkg to 'https://nuget.org'...
info :   PUT https://nuget.org/api/v2/package/
info :   Created https://nuget.org/api/v2/package/ 12797ms
info : Your package was pushed.

C:\src\FSharpFriendlyDotNet\nuget_packages>dotnet nuget push *.nupkg --source https://nuget.org
info : Pushing FSharpFriendlyDotNet.0.1.1.nupkg to 'https://nuget.org'...
info :   PUT https://nuget.org/api/v2/package/
info :   Conflict https://nuget.org/api/v2/package/ 1379ms
error: Response status code does not indicate success: 409 (A package with ID 'FSharpFriendlyDotNet' and version '0.1.1'
 already exists and cannot be modified.).


Lets see in a couple of hours if the symbols have been pushed ;)

**Comment by tomasaschan** [comment]
Hum; interesting. I was under the impression that it would automatically use https://nuget.smbsrc.net/ as the source for the symbols package. Could you try

```
dotnet push *.nupkg --source https://nuget.org --symbol-source https://nuget.smbsrc.net/
```

and see if that does the right thing? Otherwise we might have to just issue two commands (and word them smartly to not include the symbols package in the first one...).

**Comment by kbilsted** [comment]
C:\src\FSharpFriendlyDotNet\nuget_packages>dotnet nuget push *.nupkg --source https://nuget.org --symbol-source https://
nuget.smbsrc.net/
info : Pushing FSharpFriendlyDotNet.0.1.1.nupkg to 'https://nuget.org'...
info :   PUT https://nuget.org/api/v2/package/
info :   Conflict https://nuget.org/api/v2/package/ 1556ms
error: Response status code does not indicate success: 409 (A package with ID 'FSharpFriendlyDotNet' and version '0.1.1'
 already exists and cannot be modified.).

**Comment by kbilsted** [comment]
C:\src\FSharpFriendlyDotNet\nuget_packages>dotnet nuget push *.nupkg --source https://nuget.org --symbol-source https://
nuget.smbsrc.net/
info : Pushing FSharpFriendlyDotNet.0.1.2.nupkg to 'https://nuget.org'...
info :   PUT https://nuget.org/api/v2/package/
info :   Created https://nuget.org/api/v2/package/ 12898ms
info : Your package was pushed.
info : Pushing FSharpFriendlyDotNet.0.1.2.symbols.nupkg to 'https://nuget.org'...
info :   PUT https://nuget.org/api/v2/package/
info :   Conflict https://nuget.org/api/v2/package/ 513ms
error: Response status code does not indicate success: 409 (A package with ID 'FSharpFriendlyDotNet' and version '0.1.2'
 already exists and cannot be modified.).

**Comment by tomasaschan** [comment]
Argh. It doesn't seem to recognize that this is a symbols package... 🤔 I'll take a look when I get some time to spare, if you don't get to it before me...

**Comment by kbilsted** [comment]
it doesn't seem to be pushing any symbols only pushing the symbols file..

**Pull request merged**
